### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by yvz5** [GoNZooo/zig-win32#5]
Hi guys, 

appreciate your work. I am completely new to Zig and I would like to use the win32 api. I cant seem to create a window using your lib. Would you mind creating a sample for this ?

**Comment by GoNZooo** [comment]
Hi!

Just letting you know that I've taken note of this issue and I'll take a look at making an up-to-date example some time in the near future. I've also tagged it with some labels that could potentially entice newcomers to provide this before I get to it.

You're absolutely right that the library needs to be documented more clearly if it is to continue. With that said I'm unclear on the future of `zig-win32` as a lot of the types it provides are now available in the standard library or by custom libraries that slice out specific parts of Win32. Since Zig is nominally typed these will always clash with `zig-win32` (both the stdlib and other libraries, things that have the exact same structure and names will clash because they've been defined in different modules) and I'm not sure how much people are actually relying on this library for their Win32 stuff.

**Comment by yvz5** [comment]
I see your concern. To be honest, I have just cImported windows.h and windowsx.h and moved on. If you could provide idiomatic zig over win32, that would be valuable anyway. I'll close the issue then.

**Comment by GoNZooo** [comment]
Just to provide some perspective on why this was started: Zig, when I created this, couldn't properly import parts of `windows.h` and in general the files needed massaging. In part, the work was also adding linker information to the imports so one didn't have to sort that out manually in the build file. In time, I think this library has become less and less relevant as importing `windows.h` has become more and more stable.

Though I will say that the lazy nature of Zig compilation may mean that you just don't know which errors exist. This is true both of `@cImport` and `zig-win32` (which is just a post-processed `@cImport`). When you use an identifier you might learn that it's actually not correct and/or has some subtle inconsistency with something else.
